### ISSUE TITLE
x-team/wp-cli-ssh is abandoned

### ISSUE THREAD

**Issue by cycomarcooo** [xwp/wp-cli-ssh#32]
Hi,
Last time I performed a "composer update" I got this warning:
```
Package x-team/wp-cli-ssh is abandoned, you should avoid using it. No replacement was suggested.
```

Is it really abandoned?
Regards

**Comment by jonathanbardo** [comment]
@cycomarcooo Yes since this feature will be part of core wp-cli.  See https://github.com/wp-cli/wp-cli/issues/2754

**Comment by cycomarcooo** [comment]
Thank you, I had not paid attention to this new core feature 👍
